---
title: "Forecasting Competition Attempt 1"
author: "Julia Kagiliery & Cynthia Zhou"
output: pdf_document
---

```{r package, message=FALSE, warning=FALSE}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
library(readxl)
library(dplyr)
```

```{r}
HourlyData <- read_excel("./Data/load.xlsx", col_types = c("skip", 
    "date", "numeric", "numeric", "numeric", 
    "numeric", "numeric", "numeric", "numeric", 
    "numeric", "numeric", "numeric", "numeric", 
    "numeric", "numeric", "numeric", "numeric", 
    "numeric", "numeric", "numeric", "numeric", 
    "numeric", "numeric", "numeric", "numeric", 
    "numeric"))

Dates <-HourlyData[,1]

Loads <- HourlyData[,2:25]

Loads <- Loads |>
  mutate(
    DailyAverage = rowMeans(across(everything())))

AverageDaily <- cbind(Loads, Dates$date)

AverageDaily <- AverageDaily[,25:26] 

colnames(AverageDaily) <- c("DailyAve", "Date")

view(AverageDaily)
```

This is not the best way to do it but AverageDaily data set contains the average of the 24 hours (column name = DailyAve) and the date (titled "Date").

Code inspiration: https://www.geeksforgeeks.org/calculate-the-mean-of-each-row-of-an-object-in-r-programming-rowmeans-function/

```{r}
AverageDaily %>%
  ggplot(aes(y = DailyAve, x = Date)) +  # Close aes() here
  geom_line()
```

```{r}
TSDaily <- msts(AverageDaily[,1], start = c(2005, 01, 01), c(7,365))
autoplot(TSDaily)
```

```{r message=FALSE, warning=FALSE}
#create a subset for training purpose
n_for = 365+181 # remove data in 01/2010 to 06/2011
TSDaily_train <- subset(TSDaily, end = length(TSDaily)-n_for)

#create a subset for testing purpose
TSDaily_test <- subset(TSDaily, start = length(TSDaily)-n_for)

autoplot(TSDaily_train)
autoplot(TSDaily_test)

```

### Model 1: STL + ETS

```{r ETS, echo=TRUE, message=FALSE, warning=FALSE}
#Test the model by comparing data in 2010
#Fit and forecast STL + ETS model to data
ETS_fit_test <-  stlf(TSDaily_train, h=n_for)

#Plot model + observed data
autoplot(TSDaily) +
  autolayer(ETS_fit_test, series="STL + ETS",PI=FALSE) +
  ylab("Load")
```

###Model 2: TBATS()
```{r TBATS, echo=TRUE, message=FALSE, warning=FALSE}
TSDaily_trainNA<-na.approx(TSDaily_train)
TBATS_test <- tbats(TSDaily_trainNA)
TBATS_for <- forecast(TBATS_test, h=n_for)
#Plot model + observed data
autoplot(TSDaily) +
  autolayer(TBATS_for, series="TBATS test",PI=FALSE) +
  ylab("load")
```

Model 3: ARIMA + FOURIER terms

```{r ARIMA, echo=TRUE, message=FALSE, warning=FALSE}
#Fit arima model with fourier terms as exogenous regressors
# seasonal = FALSE is the same as P=D=Q=0

ARIMA_Four_fit <- auto.arima(TSDaily_train, 
                             seasonal=FALSE,  #do not use sarima
                             lambda=0,
                             xreg=fourier(TSDaily_train, 
                                          K=c(2,12)))

#Forecast with ARIMA fit
#also need to specify h for fourier terms
ARIMA_Four_for <- forecast(ARIMA_Four_fit,
                           xreg=fourier(TSDaily_train,
                                        K=c(2,12),
                                        h=n_for),
                           h=n_for
                           ) 

#Plot model + observed data
autoplot(TSDaily) +
  autolayer(ARIMA_Four_for, series="ARIMA_FOURIER test",PI=FALSE) +
  ylab("Load")

```


Model 4: Neural Network
```{r Neural Network, warning=FALSE}
NN_fit <- nnetar(TSDaily_train,
                 p=2,
                 P=2,
                 xreg=fourier(TSDaily_train, K=c(2,12)))

NN_for <- forecast(NN_fit, h=n_for,xreg=fourier(TSDaily_train, 
                                          K=c(2,12),h = 31))

#Plot model + observed data
autoplot(TSDaily) +
  autolayer(NN_for, series="Neural Network test",PI=FALSE)+
  ylab("Load")

```

### Performance check
```{r warning=FALSE}

#Model 1: STL + ETS
ETS_scores <- accuracy(ETS_fit_test$mean, TSDaily_test)  

#Model 2: TBATS
TBATS_scores <- accuracy(TBATS_for$mean,TSDaily_test)

# Model 3: ARIMA + Fourier
ARIMA_scores <- accuracy(ARIMA_Four_for$mean,TSDaily_test)

# Model 4:  Neural Network 
NN_scores <- accuracy(NN_for$mean,TSDaily_test)

scores <- as.data.frame(
  rbind(ETS_scores, ARIMA_scores, TBATS_scores, NN_scores)
  )
row.names(scores) <- c("STL+ETS", "ARIMA+Fourier","TBATS","NN")

kbl(scores, 
      caption = "Forecast Accuracy for Daily Active Power",
      digits = array(5,ncol(scores))) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "hold_position") %>%
  #highlight model with lowest RMSE
  kable_styling(latex_options="striped", stripe_index = which.min(scores[,"RMSE"]))
```

### Output
```{r output}
date <- seq(as.Date("2011-07-01"), as.Date("2011-07-31"), by = "day")
#ETS
ETS_fit <-  stlf(TSDaily,h=31)
load1 <- ETS_fit$mean
ETS_output <- cbind.data.frame(date, load1)
write.csv(ETS_output, "ETS_output.csv", row.names = FALSE)

#TBATS
TSDailyNA <- na.approx(TSDaily)
TBATS_for <- tbats(TSDailyNA)
TBATS_fit <- forecast(TBATS_for, h=31)
load2 <- TBATS_fit$mean
TBATS_output <- cbind.data.frame(date, load2)
write.csv(TBATS_output, "TBATS_output.csv", row.names = FALSE)

#Arima
ARIMA_Four_fit2 <- auto.arima(TSDaily, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(TSDaily, 
                                          K=c(2,12)))
ARIMA_2for <- forecast(ARIMA_Four_fit2,
                           xreg=fourier(TSDaily,
                                        K=c(2,12),
                                        h=31),
                           h=31
                           ) 
load3 <- ARIMA_2for$mean
ARIMA_output <- cbind.data.frame(date, load3)
write.csv(ARIMA_output, "ARIMA_output.csv", row.names = FALSE)

#NN
NN_fit <- nnetar(TSDaily,
                 p=2,
                 P=2,
                 xreg=fourier(TSDaily, K=c(2,12)))

NN_for <- forecast(NN_fit, h=31,xreg=fourier(TSDaily, 
                                          K=c(2,12),h = 31))
load4 <- NN_for$mean
NN_output <- cbind.data.frame(date, load4)
write.csv(NN_output, "NN_output.csv", row.names = FALSE)
```